import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Search } from '../components/Search'
import { React } from 'react'

export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Aggrated</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Aggrate!
        </h1>

        <p className={styles.description}>
          Your one stop for all things{' '}
          <code className={styles.code}>rated</code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>MAL &rarr;</h2>
            <p>Find in-depth information about your favourite animes.</p>
            <Search category = {'MyAnimeList'}/>
          </a>

          <a className={styles.card}>
            <h2>IMDB &rarr;</h2>
            <p>Learn more about your favorite TV Shows!</p>
            <Search category = {'IMDB'}/>
          </a>

        </div>
      </main>

    </div>
  )
}
